吴恩达 机器学习 课程 练习册

求逆矩阵

In [1]:
import numpy as np

In [13]:
x=[[3,4],[2,16]]

In [14]:
a=np.mat(x)

In [15]:
a.all

<bound method matrix.all of matrix([[ 3,  4],
        [ 2, 16]])>

In [20]:
b=a.I  # 求逆矩阵
c=a.T # 求转置矩阵

In [17]:
 b

matrix([[ 0.4  , -0.1  ],
        [-0.05 ,  0.075]])

In [19]:
a*b    #矩阵*逆矩阵=单位矩阵

matrix([[1., 0.],
        [0., 1.]])

In [21]:
c

matrix([[ 3,  2],
        [ 4, 16]])