吴恩达 机器学习 课程 练习册

求逆矩阵

In [3]:
import numpy as np

In [4]:
x=[[3,4],[2,16]]

In [5]:
print(x)

[[3, 4], [2, 16]]


In [9]:
a=np.mat(x)

In [10]:
a.all

<bound method matrix.all of matrix([[ 3,  4],
        [ 2, 16]])>

In [20]:
b=a.I  # 求逆矩阵
c=a.T # 求转置矩阵

In [17]:
 b

matrix([[ 0.4  , -0.1  ],
        [-0.05 ,  0.075]])

In [19]:
a*b    #矩阵*逆矩阵=单位矩阵

matrix([[1., 0.],
        [0., 1.]])

In [21]:
c

matrix([[ 3,  2],
        [ 4, 16]])

In [24]:
a.shape ,type(a), a.data.itemsize,a.data.tolist

((2, 2), numpy.matrix, 8, <function memoryview.tolist()>)

In [29]:
a.data.tolist()

[[3, 4], [2, 16]]

In [12]:
d=np.arange(1,100,2)

In [17]:
d.size ,d.shape

(50, (50,))

In [37]:
B=np.arange(1,101).reshape(5,20)

In [38]:
type(B)

numpy.ndarray

In [39]:
C=np.mat(B)

In [40]:
C

matrix([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
          34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
          54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
          74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
          94,  95,  96,  97,  98,  99, 100]])

In [74]:
C.T,C.T.shape

(matrix([[  1,  21,  41,  61,  81],
         [  2,  22,  42,  62,  82],
         [  3,  23,  43,  63,  83],
         [  4,  24,  44,  64,  84],
         [  5,  25,  45,  65,  85],
         [  6,  26,  46,  66,  86],
         [  7,  27,  47,  67,  87],
         [  8,  28,  48,  68,  88],
         [  9,  29,  49,  69,  89],
         [ 10,  30,  50,  70,  90],
         [ 11,  31,  51,  71,  91],
         [ 12,  32,  52,  72,  92],
         [ 13,  33,  53,  73,  93],
         [ 14,  34,  54,  74,  94],
         [ 15,  35,  55,  75,  95],
         [ 16,  36,  56,  76,  96],
         [ 17,  37,  57,  77,  97],
         [ 18,  38,  58,  78,  98],
         [ 19,  39,  59,  79,  99],
         [ 20,  40,  60,  80, 100]]), (20, 5))

In [44]:
C[4,19]

100

In [77]:
C[1,2:].max

<bound method matrix.max of matrix([[23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
         39, 40]])>

In [48]:
C[3:5,1:] ,C[:,1]

(matrix([[ 62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
           75,  76,  77,  78,  79,  80],
         [ 82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
           95,  96,  97,  98,  99, 100]]), matrix([[ 2],
         [22],
         [42],
         [62],
         [82]]))

In [54]:
D=np.mat(np.arange(1,21).reshape(20,1))
D

matrix([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20]])

矩阵的相乘运算

In [56]:
B*D ,type(B*D)

(matrix([[ 2870],
         [ 7070],
         [11270],
         [15470],
         [19670]]), numpy.matrix)

In [57]:
E=-1

In [59]:
import math

In [78]:
abs(-1),abs(E), math.asin(E),math.log(4)  ,magic([1,2,3])

NameError: name 'magic' is not defined